### ISSUE TITLE
Make Subreddit and Reddit-wide page queries more storage efficient

### ISSUE THREAD

**Issue by natematias** [c4fcm/CivilServant#32]
Reduce how much we store in the json field -- probably:
- ID
- order
- author
- the number of upvotes and comments

**Comment by natematias** [comment]
Make a data migration to prune past json_dict fields to be more storage efficient in this way.

**Comment by mmou** [comment]
pruned_post = {
                'id': new_post['id'],
                'author': new_post['author'],
                'num_comments': new_post['num_comments'],
                'downs': new_post['downs'],
                'ups': new_post['ups'], 
                'score': new_post['score']                                             
                }
