### ISSUE TITLE
Add Subreddit unique identifier to subreddit_page model

### ISSUE THREAD

**Issue by natematias** [c4fcm/CivilServant#33]
And also create a data migration to back-fill the data

**Comment by natematias** [comment]
@mmou the code is not storing the subreddit_id to the database when the record is created.

**Comment by natematias** [comment]
Also, could we please add the time a post was created to the json archive in the subreddit_page model? Thanks!

**Comment by mmou** [comment]
don't know if you get emails for pull requests, but check out https://github.com/c4fcm/CivilServant/pull/38 for fixes.
